// Each new term in the Fibonacci sequence is generated by adding the previous 
// two terms. By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 90,...
//
//  By condidering the terms in the Fibonachi sequence whose values do not 
//  exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

void main() { 
    int sum = 0;
    int a = 1;
    int b = a;
    
    int c;
    for (c = a + b; c < 4000000;) {
        c = a + b;
        a = b;
        b = c;
        
        if (c % 2 == 0) {
            sum += c;
        }
    }

    printf("%d\n", sum);
}
